KtSPR--L3-T5-обратный парсинг шахматного хода
DenisGubernatorov/KotlinSprint pull request #11
Opened 2024-06-10 21:38 UTC by DenisGubernatorov

Парсинг полученной строки с ходом в отдельные переменные (откуда, куда, номер хода)

2024-06-10 21:40 UTC, DenisGubernatorov commented
Странно, но для этого PR  у меня гитхаб ругается что в заголовке могут быть скрытые символы. Хотя, как обычно, набирал

2024-06-11 07:48 UTC, ievetrovdev requested changes
На будущее
В названии ветки кириллицу не используем. Все буквы декодируются в unicode символы, не входящие в диапазон таблицы ASCII. В следующий раз только англ. буквами делаем название.
Название ветки также должно содержать префикс проекта с номером урока и задачи, чтобы они все были уникальны и в них можно было легко ориентироваться. Слова в названии веток разделяются дефисами. Например, “KS-1-1-create-smth”.

2024-06-11 07:48 UTC, ievetrovdev commented on src/main/kotlin/lesson3/lesson3_task5.kt
> +    val turnFrom = receivedData.substring(0,2)
Неплохо, рабочее решение! Но попробуем более оптимальное решение)
Предлагаю применить функцию split(), обрати внимание какие параметры она умеет принимать.

2024-06-11 15:24 UTC, DenisGubernatorov commented on src/main/kotlin/lesson3/lesson3_task5.kt
> +    val turnFrom = receivedData.substring(0,2)
Перевел на использование split. Спасибо.

2024-06-12 05:27 UTC, ievetrovdev approved these changes

2024-06-12 06:38 UTC, merged