KS-06-02-timer
DenisGubernatorov/KotlinSprint pull request #27
Opened 2024-08-11 14:37 UTC by DenisGubernatorov

Реализация таймера постановки программы на паузу. Пользователь должен ввести количество секунд, на сколько должна приостановиться программа. В конце пользователю выведется сообщение с количеством прошедших секунд

2024-08-11 17:45 UTC, ievetrovdev requested changes

2024-08-11 17:45 UTC, ievetrovdev commented on src/main/kotlin/lesson6/lesson6_task2.kt
> +    }
Здесь можно обойтись без цикла

2024-08-12 10:06 UTC, DenisGubernatorov commented on src/main/kotlin/lesson6/lesson6_task2.kt
> +    }
Оптимизировал

2024-08-12 22:50 UTC, ievetrovdev approved these changes
Все успел, отлично!

2024-08-13 12:50 UTC, merged