KS-07-05-password-generator-update
DenisGubernatorov/KotlinSprint pull request #31
Opened 2024-08-12 14:40 UTC by DenisGubernatorov

1) Генерация пароля с использованием диапазонов 'A'..'Z','a'..'z' и '0'..'9' 2) Пользователю не позволяется ввести длину пароля меньше чем 6 символов

2024-08-12 20:17 UTC, ievetrovdev requested changes

2024-08-12 20:17 UTC, ievetrovdev commented on src/main/kotlin/lesson7/lesson7_task5.kt
> +val range = ('A'..'Z').toList() + ('a'..'z').toList() + (0..9).toList()
Лучше объявить эту переменную внутри `fun main()`

2024-08-12 20:17 UTC, ievetrovdev commented on src/main/kotlin/lesson7/lesson7_task5.kt
> +    for (i in 0..passwordLength) generatedPassword += range.random()
Ошибка в диапазоне цикла. Пароль генерируется на один символ больше, чем требуется.

2024-08-12 21:22 UTC, DenisGubernatorov commented
Поправил

2024-08-13 07:53 UTC, ievetrovdev requested changes
Окей код работает.  Стоит еще конечную строку с паролем перемешать. Сделать это можно, используя extension `shuffle().`
Но обрати внимание с какими типами работает   `shuffle().`. Тебе необходимо чтобы твой пароль состоял из трёх составных частей, у тебя это прописано в `val range` , но немного не верно указано  **toList()** . Тебе нужно поработать с типом  `Char`  `CharRange`

2024-08-13 15:34 UTC, DenisGubernatorov commented
С range  понял. Тип объектов в list  был действительно не Char.  Но вот дополнительное перемешивание результирующего пароля не лишнее? Из-за псевдослучайноси? Но ведь по дефолту генерация зависит от параметров системы. Вроде как время в этом учавствует.

2024-08-13 19:54 UTC, ievetrovdev approved these changes
В обычных условиях генерация пароля с помощью стандартных методов случайных чисел не должна зависеть от параметров системы. Что касается дополнительного перемешивания сгенерированного пароля, то лишним точно не будет.

2024-08-13 20:21 UTC, merged