KS-08-03-ingredients-update
DenisGubernatorov/KotlinSprint pull request #39
Opened 2024-08-13 21:55 UTC by DenisGubernatorov

1) Проверка, входит ли ингредиент в рецепт без использования for

2024-08-13 22:53 UTC, ievetrovdev requested changes

2024-08-13 22:53 UTC, ievetrovdev commented on src/main/kotlin/lesson8/lesson8_task3.kt
> +    ) {
Лучше было бы использовать in

2024-08-14 13:07 UTC, DenisGubernatorov commented on src/main/kotlin/lesson8/lesson8_task3.kt
> +    ) {
Перевел на использование in. Но тогда пришлось преобразовывать сам массив, что бы сохранить логику сравнения без учета региста. Просто  in проверяет на строгое соотвествие. Конечно в ТЗ не указано, что регистр не нужно учитывать. Но само собой напрашивается

2024-08-14 20:12 UTC, ievetrovdev approved these changes
Все верно, отлично!

2024-08-15 10:22 UTC, merged