KS-09-03-servings-count
DenisGubernatorov/KotlinSprint pull request #46
Opened 2024-08-15 12:20 UTC by DenisGubernatorov

1) Расчет необходимого количества ингредиентов на количество порций омлета, указанное пользователем

2024-08-15 21:23 UTC, ievetrovdev requested changes

2024-08-15 21:23 UTC, ievetrovdev commented on src/main/kotlin/lesson9/lesson9_task3.kt
> +    servings.replaceAll { it * servingCount }
Используй функцию map для этих целей) и в каждую итерацию будем перемножать элемент коллекции

2024-08-16 13:55 UTC, DenisGubernatorov commented on src/main/kotlin/lesson9/lesson9_task3.kt
> +    servings.replaceAll { it * servingCount }
Что бы не зависать на задаче, перевел на использование map.

2024-08-17 11:38 UTC, ievetrovdev approved these changes

2024-08-17 17:47 UTC, merged