KS-09-04-user-ingredients-input
DenisGubernatorov/KotlinSprint pull request #47
Opened 2024-08-15 15:58 UTC by DenisGubernatorov

1) Пользователь вводит название ингредиентов.
2) Список ингредиентов разбивается по разделителю из ТЗ и помещается в список 3) Формируется отсортированная копия списка и выводится в консоль

2024-08-15 21:26 UTC, ievetrovdev requested changes

2024-08-15 21:26 UTC, ievetrovdev commented on src/main/kotlin/lesson9/lesson9_task4.kt
> +    val splitted = userIngredients.split(", ").toList()
Можно сразу вызвать sorted, toList() не нужен

2024-08-16 14:03 UTC, DenisGubernatorov commented on src/main/kotlin/lesson9/lesson9_task4.kt
> +    val splitted = userIngredients.split(", ").toList()
+

2024-08-16 18:39 UTC, ievetrovdev approved these changes
Все верно, отличное решение!

2024-08-17 07:31 UTC, merged