KS-11-01-two-entity-of-class-user
DenisGubernatorov/KotlinSprint pull request #56
Opened 2024-08-18 20:30 UTC by DenisGubernatorov

1) Определен класс User, со своими свойствами
2) Создание 2х объектов класса User  и вывод значений свойств объектов в консоль

2024-08-19 07:12 UTC, ievetrovdev requested changes

2024-08-19 07:12 UTC, ievetrovdev commented on src/main/kotlin/lesson11/lesson11_task1.kt
> +private fun showInfo(user: User) {
Вообще метод лучше поместить в сам класс, тогда в него не нужно будет передавать объект, все поля класса и так будут доступны

2024-08-19 22:05 UTC, DenisGubernatorov commented on src/main/kotlin/lesson11/lesson11_task1.kt
> +private fun showInfo(user: User) {
Сделал

2024-08-20 07:08 UTC, ievetrovdev approved these changes

2024-08-20 18:53 UTC, merged