KS-13-03 phone directory three
DenisGubernatorov/KotlinSprint pull request #70
Opened 2024-08-23 21:01 UTC by DenisGubernatorov

1) Компании добавляются в общий список
2) Выводятся названия только существующих компаний

2024-08-23 21:28 UTC, ievetrovdev requested changes

2024-08-23 21:28 UTC, ievetrovdev commented on src/main/kotlin/lesson13/lesson13_task1.kt
Обрати внимание во вкладке с изменениями в этот ПР попал лишний файл (13-1 который не относится к этой задаче). Скорее всего ветка создалась не из мастера. Давай выпилим его (надо в этой ветке физически удалить файл из проекта, сделать коммит удаления и запушить. и отправить ПР снова на ревью).

2024-08-24 11:59 UTC, DenisGubernatorov commented on src/main/kotlin/lesson13/lesson13_task1.kt
Ветка создавалась из мастера. Но в первом коммите я не в том файле написал код. В коммите 73e3fb12a1179494acd2d6c811aec668bec2705e я переносил код из одного файла в другой.

2024-08-24 12:03 UTC, DenisGubernatorov commented on src/main/kotlin/lesson13/lesson13_task1.kt
Файл удалил

2024-08-24 19:38 UTC, ievetrovdev approved these changes
Все верно, отличное решение!

2024-08-25 12:14 UTC, closed without merging