KS-13-04 phone directory four
DenisGubernatorov/KotlinSprint pull request #71
Opened 2024-08-23 21:03 UTC by DenisGubernatorov

1) Данные для создания записи в справочнике вводятся через консоль
2) Если пользователь не ввел телефон или ввел не цифры, то запись не создается. Выводится сообщение о невозможности создания. Далее спрашивает продолжить или нет
3) Если пользователь не ввел название компании, то вместо нее записывается null
4) После создания записи в справочнике пользователя спрашивает продолжить или нет

2024-08-23 21:31 UTC, ievetrovdev requested changes

2024-08-23 21:31 UTC, ievetrovdev commented on src/main/kotlin/lesson13/lesson13_task4.kt
> +            // гарантированно не null. Почему так?
Не всегда учитываются условия в  идеа, и такие комментарии нужно  оставлять в самом ПР, а  не в коде,  давай уберем  его

2024-08-24 12:06 UTC, DenisGubernatorov commented on src/main/kotlin/lesson13/lesson13_task4.kt
> +            // гарантированно не null. Почему так?
Сделал

2024-08-24 19:39 UTC, ievetrovdev approved these changes
Все верно, отличное решение!

2024-08-25 11:46 UTC, merged