KtSPR--L2-T3-прибытие-поезда
DenisGubernatorov/KotlinSprint pull request #8
Opened 2024-06-09 16:04 UTC by DenisGubernatorov

Расчет прибытие поезда. Учитывается переход на следующие сутки

2024-06-09 20:53 UTC, ievetrovdev requested changes

2024-06-09 20:53 UTC, ievetrovdev commented on src/main/kotlin/lesson2/lesson2_task3.kt
> +    println("$arriveHours:$arriveMinutes")
В задании сказано, что время прибытия нужно вывести в формате [часы:минуты], где часы и минуты должны быть представлены двумя цифрам.

2024-06-10 18:13 UTC, DenisGubernatorov commented
Исправлен формат вывода времени. Выводится с ведущими нулями

2024-06-10 19:43 UTC, ievetrovdev approved these changes
Отличное решение, все верно!

2024-06-10 21:37 UTC, merged