KS-15-02-Weather-Station-Stats
DenisGubernatorov/KotlinSprint pull request #81
Opened 2024-08-26 20:29 UTC by DenisGubernatorov

1) Реализация абстрактного класса WeatherStationStats имплементирующего интерфейс DataSend с методом отправки данных 2) Класс Temperature, переопределяющий логику отправки данных 3) 2) Класс PrecipitationAmount, переопределяющий логику отправки данных

2024-08-27 15:14 UTC, ievetrovdev requested changes
Не соответствует ТЗ, давай прочитаем ТЗ еще раз и сделаем как там сказано)

2024-08-27 15:14 UTC, ievetrovdev commented on src/main/kotlin/lesson15/lesson15_task2.kt
> +interface DataSend {
Зачем нам интерфейс в данной задаче?)

2024-08-27 18:05 UTC, DenisGubernatorov commented on src/main/kotlin/lesson15/lesson15_task2.kt
> +interface DataSend {
Интерфейс убрал. В классе-родителе добавил абстрактный метод отправки данных.

2024-08-28 09:36 UTC, ievetrovdev requested changes
Все же рекомендую перечитать ТЗ еще раз, оставил комментов

2024-08-28 09:36 UTC, ievetrovdev commented on src/main/kotlin/lesson15/lesson15_task2.kt
> +abstract class WeatherStationStats {
Этот абстрактный класс используется в качестве базового класса, от которого наследуются более конкретные классы, описывающие данные метеостанции. В данной задачи это необходимо для демонстрации полиморфизма.

2024-08-28 09:36 UTC, ievetrovdev commented on src/main/kotlin/lesson15/lesson15_task2.kt
> +    abstract fun doSendData()
В ТЗ написано `Реализуй логику имитации отправки сообщения на сервер в классе WeatherServer`
Данные метеостанции не должны отвечать за отправку самих себя)

2024-08-28 09:36 UTC, ievetrovdev commented on src/main/kotlin/lesson15/lesson15_task2.kt
> +class Temperature : WeatherStationStats() {
Поскольку данные температуры и количества осадков обычно содержат какие-то значения, предлагаю добавить соответствующие поля в эти классы)

2024-08-29 18:38 UTC, ievetrovdev requested changes

2024-08-29 18:38 UTC, ievetrovdev commented on src/main/kotlin/lesson15/lesson15_task2.kt
> +        when (message) {
Хорошо, но предлагаю для большей безопасности учесть вариант, что могут прийти данные, не относящиеся к этим двум классам.

2024-08-30 11:09 UTC, ievetrovdev approved these changes
Теперь корректно, аппрув!

2024-08-30 18:03 UTC, merged