KS-15-01-animals-move
DenisGubernatorov/KotlinSprint pull request #82
Opened 2024-08-26 20:29 UTC by DenisGubernatorov

1) Реализованы интерфейсы Fly и Swim  с дефолтной реализацией методов doFle и doSwim  соответственно 2) Создан классы Carp(Карась) Seagull(Чайка) и Duck(Утка)  которые реализуют интерфейсы типа передвижения

2024-08-27 15:04 UTC, ievetrovdev requested changes

2024-08-27 15:04 UTC, ievetrovdev commented on src/main/kotlin/lesson15/lesson15_task1.kt
> +interface Fly {
Хорошо, но нарушается принцип единой ответственности (см. [SOLID](https://habr.com/ru/companies/productivity_inside/articles/505430/)) потому что теперь я по ошибке или случайно могу заставить карася полететь и все сломается

2024-08-27 15:04 UTC, ievetrovdev commented on src/main/kotlin/lesson15/lesson15_task1.kt
> +    Fly
Здесь можно в одну строку)

2024-08-27 18:48 UTC, DenisGubernatorov commented on src/main/kotlin/lesson15/lesson15_task1.kt
> +    Fly
> Здесь можно в одну строку)
А у меня klint подчеркивает. И при коммите стоит реформат кода
![image](https://github.com/user-attachments/assets/550670cc-4917-415e-bcb2-72efc091c6b1)
![image](https://github.com/user-attachments/assets/c4974590-3193-446b-a07f-da8e0e4d4940)

2024-08-28 09:46 UTC, ievetrovdev requested changes
Классы `Carp`, `Seagull`, и `Duck` реализуют интерфейсы, но не реализуют методы этих интерфейсов (то есть методы `doFly` и `doSwim` не переопределяются явно). Несмотря на то, что в Kotlin интерфейсы могут иметь методы с реализацией, явное переопределение методов в классах помогает избежать ошибок и улучшает читаемость кода.

2024-08-29 07:53 UTC, DenisGubernatorov commented
> Классы `Carp`, `Seagull`, и `Duck` реализуют интерфейсы, но не реализуют методы этих интерфейсов (то есть методы `doFly` и `doSwim` не переопределяются явно). Несмотря на то, что в Kotlin интерфейсы могут иметь методы с реализацией, явное переопределение методов в классах помогает избежать ошибок и улучшает читаемость кода.

Ну да. Я как бы и учитывал момент, что в интерфейсах может быть дефолтная реализация метода

2024-08-29 18:36 UTC, ievetrovdev commented
> > Классы `Carp`, `Seagull`, и `Duck` реализуют интерфейсы, но не реализуют методы этих интерфейсов (то есть методы `doFly` и `doSwim` не переопределяются явно). Несмотря на то, что в Kotlin интерфейсы могут иметь методы с реализацией, явное переопределение методов в классах помогает избежать ошибок и улучшает читаемость кода.
> 
> Ну да. Я как бы и учитывал момент, что в интерфейсах может быть дефолтная реализация метода

Это не совсем корректная реализация поведения по умолчанию. 
Все же интерфейсы предназначены для определения поведения, а не для хранения состояния, а определяя свойство name в интерфейсе, любой класс, реализующий этот интерфейс, зависит от этого свойства. Но что, если классу не нужно иметь это свойство, а нужно только выполнять действие, описанное в интерфейсе?

2024-08-29 18:37 UTC, ievetrovdev approved these changes
Теперь все корректно, апрув!

2024-08-29 18:47 UTC, merged