KS-15-04-Music-Shop
DenisGubernatorov/KotlinSprint pull request #83
Opened 2024-08-29 15:06 UTC by DenisGubernatorov

1) Интерфейс для реализации метода поиска аксессуара для инструмента 2) Класс Instrument. Поля класса название инструмента и количество на складе. Реализует интерфейс поиска аксессуара. 3) Класс Accessories. Поля класса название инструмента и количество на складе.

2024-08-29 18:52 UTC, ievetrovdev requested changes

2024-08-29 18:52 UTC, ievetrovdev commented on src/main/kotlin/lesson15/lesson15_task4.kt
> +class Accessories(
Для более корректной иерархии нужен еще некий базовый класс для товара с общими для всех категорий полями.

2024-08-30 18:47 UTC, DenisGubernatorov commented on src/main/kotlin/lesson15/lesson15_task4.kt
> +class Accessories(
Сделал

2024-08-30 20:23 UTC, ievetrovdev approved these changes
Все верно, отличное решение!

2024-08-30 20:53 UTC, ievetrovdev commented
Только это не Задача 1 Урока 16, потому отклонено будет

2024-09-01 11:51 UTC, merged