KS-16-04-internet-shop-order
DenisGubernatorov/KotlinSprint pull request #89
Opened 2024-08-30 19:58 UTC by DenisGubernatorov

1) Создан класс для заказа.
2) Номер заказа генерится случайным образом и недоступен извне 3) Публичный метод requestToChangeStage запроса на изменения заказа. Возвращает изменена стадия или нет 4) приватный метод acceptRequestByManager подтверждения. Пока "заглушка" 5) Стадии заказ отдельным enum Stage

2024-08-30 21:07 UTC, ievetrovdev requested changes

2024-08-30 21:07 UTC, ievetrovdev commented on src/main/kotlin/lesson16/lesson16_task4.kt
> +    private val orderNum = (1..10_000).random()
Такая генерация номера не верна, есть вероятность создать два заказа с одним номером, лучше передавать его при создании

2024-09-01 13:37 UTC, DenisGubernatorov commented on src/main/kotlin/lesson16/lesson16_task4.kt
> +    private val orderNum = (1..10_000).random()
Переделал

2024-09-01 22:06 UTC, ievetrovdev approved these changes
Все верно, отличное решение!

2024-09-02 13:39 UTC, merged