KS-16-05-RPG
DenisGubernatorov/KotlinSprint pull request #90
Opened 2024-09-01 13:28 UTC by DenisGubernatorov

1) Создан базовый класс для персонажа. В конструкторе можно установить базовые характеристики здоровья и силы удара и количества здоровья которое восстанавливается по умолчанию 2) Интерфейс BaseCharacterActions реализует базовые действия для всех персонажей. 3) Класс Warrior наследник Character и реализующий BaseCharacterActions

2024-09-01 13:30 UTC, DenisGubernatorov commented
Main  реализован не очень красиво. Там можно было сделать через ввод какое действие совершить и для дамага дополнитльно вводить количество полученного урона. Но решил не усложнять в рамках задачи

2024-09-01 22:04 UTC, ievetrovdev requested changes

2024-09-01 22:04 UTC, ievetrovdev commented on src/main/kotlin/lesson16/lesson16_task5.kt
> +        return isDead(health)
Персонажа заставляют умереть при каждом получении урона. Надо бы вынести вызов этой функции в отдельное условие

2024-09-01 22:04 UTC, ievetrovdev commented on src/main/kotlin/lesson16/lesson16_task5.kt
> +    protected abstract fun isDead(param: Int): Boolean
По заданию: "Добавить **приватный** метод, который вызывается, если при получении урона заканчивается здоровье.", а тут protected

2024-09-01 22:04 UTC, ievetrovdev commented on src/main/kotlin/lesson16/lesson16_task5.kt
> +        health -= getDamage
Следует вычитать из здоровья абсолютное значение дамага (есть функция).

2024-09-02 21:00 UTC, ievetrovdev requested changes

2024-09-02 21:00 UTC, ievetrovdev commented on src/main/kotlin/lesson16/lesson16_task5.kt
> +    override fun getDamage(getDamage: Int): Int {
Согласно ТЗ: "Добавить приватный метод, **который вызывается, если при получении урона заканчивается здоровье**." - Нужно добавить в этот метод checkIsDead. Получение урона должно автоматически убивать.

2024-09-03 19:25 UTC, DenisGubernatorov commented on src/main/kotlin/lesson16/lesson16_task5.kt
> +    override fun getDamage(getDamage: Int): Int {
Если честно, то не совсем понимаю. В первоначальном варинате и вызвался метод isDead из метода getDamage (https://github.com/DenisGubernatorov/KotlinSprint/pull/90#discussion_r1740201263). Единственный момент, что он был prtected, а не privat. Но ведь, по сути, protected мотоды видны в самом классе и в классах наследниках. Но вот обратиться к этому методу из экземпляра класса наследники нельзя. Что ответчает требованию приватности. А если не делать protected в классе родителе, то его нельзя переопределить в наследниках. И пришлось добавлять лишнюю, на мой взгляд, логику вызова через public метод.

2024-09-03 21:19 UTC, ievetrovdev commented on src/main/kotlin/lesson16/lesson16_task5.kt
> +    override fun getDamage(getDamage: Int): Int {
В целом, тут не обязательно было делать такую иерархию, да и само задание делает такое не очень удобным, впрочем, главное добиться того, что бы персонаж мог умереть при получении урона, без дополнительных манипуляций и методов

2024-09-03 21:20 UTC, ievetrovdev approved these changes
Все верно, отличное решение!

2024-09-04 16:38 UTC, merged